server:
  port: 8081
  servlet:
    context-path: /second-service

spring:
  application:
    name: second-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
