server:
  port: 8082
  servlet:
    context-path: /third-service

spring:
  application:
    name: third-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
