server:
  port: 8080
  servlet:
    context-path: /first-service

spring:
  application:
    name: first-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
